// CrisisResponseTemplates.swift
// EmberHearth
//
// Pre-written response templates for each crisis tier.
// These responses are carefully crafted to:
// - Express care without attempting therapy
// - Provide crisis resources immediately
// - Not probe or ask follow-up questions about the crisis
// - Remain available for normal conversation
//
// Reference: docs/specs/crisis-safety-protocols.md, Part 3

import Foundation

/// Contains pre-written response templates for each crisis tier.
///
/// These responses are NOT generated by the LLM — they are static, reviewed text
/// that is prepended to (or replaces) the LLM's normal response when crisis signals
/// are detected in the user's message.
///
/// IMPORTANT: These templates have been reviewed for:
/// - Compassion without over-engagement
/// - Clear resource information
/// - No probing questions about the crisis
/// - Appropriate boundaries (Ember is not a therapist)
enum CrisisResponseTemplates {

    /// Returns the appropriate crisis response for the given tier.
    ///
    /// - Parameter tier: The detected crisis tier.
    /// - Returns: A pre-written response string to send to the user.
    static func response(for tier: CrisisTier) -> String {
        switch tier {
        case .tier1:
            return tier1Response
        case .tier2:
            return tier2Response
        case .tier3:
            return tier3Response
        }
    }

    // MARK: - Tier 1: Immediate Crisis

    /// Response for Tier 1 (immediate crisis): Active suicidal ideation, imminent danger.
    ///
    /// Behavioral rules:
    /// - Express care without escalating
    /// - Provide resources IMMEDIATELY
    /// - Do NOT engage with crisis content
    /// - Do NOT ask probing questions
    /// - Do NOT offer advice or coping strategies
    /// - Include 988, Crisis Text Line, and 911
    static let tier1Response = """
    I hear you, and I'm really concerned about what you're sharing with me right now.

    Please reach out to someone who can help:

    988 Suicide & Crisis Lifeline -- Call or text 988 (available 24/7)
    Crisis Text Line -- Text HOME to 741741
    Emergency -- Call 911 if you're in immediate danger

    I care about you, and I want you to get support from people who are trained to help. I'm here for everyday things, but right now you deserve real human support.

    Will you reach out to one of these resources?
    """

    // MARK: - Tier 2: Serious Concern

    /// Response for Tier 2 (serious concern): Passive ideation, ongoing self-harm.
    ///
    /// Behavioral rules:
    /// - Acknowledge the difficulty
    /// - Express care without therapeutic engagement
    /// - Provide resources clearly
    /// - Gently encourage professional support
    /// - Remain available for non-crisis conversation
    static let tier2Response = """
    I can hear that you're going through something really hard. That takes courage to share.

    I want to make sure you have support:

    988 Suicide & Crisis Lifeline -- Call or text 988 anytime
    Crisis Text Line -- Text HOME to 741741

    I'm not a counselor, but I do care about you. These folks are experts at helping people through tough times. Would you consider reaching out?

    I'm here for everyday things, and I'll still be here after you talk to someone.
    """

    // MARK: - Tier 3: Potential Concern

    /// Response for Tier 3 (potential concern): Vague references, indirect signals.
    ///
    /// Behavioral rules:
    /// - Acknowledge without over-reacting
    /// - Mention resources casually but clearly
    /// - Normalize seeking help
    /// - Offer to continue with other topics
    /// - Don't push or probe
    static let tier3Response = """
    That sounds really difficult. I want you to know that support is available if you ever need it:

    988 Suicide & Crisis Lifeline -- Call or text 988
    Crisis Text Line -- Text HOME to 741741

    I'm here to help with day-to-day stuff, but if you're ever struggling, these resources are available 24/7 with people who really understand.

    Is there something I can help you with today?
    """

    // MARK: - Follow-Up Response

    /// Response when user continues discussing crisis after initial resource referral.
    ///
    /// Used when the user has already received resources but continues to discuss
    /// crisis topics. Ember gently redirects without being dismissive.
    static let followUpRedirect = """
    I really appreciate you trusting me with this. It means a lot.

    I want to be honest with you: I'm an AI assistant, and I'm not equipped to help with what you're going through right now. The people at 988 are real humans who specialize in exactly this, and they won't judge you.

    Can I help you with anything else right now -- maybe something practical or a distraction?
    """

    /// Response when user has refused resources multiple times.
    ///
    /// Ember backs off the strong referral but leaves the door open.
    /// After this, Ember returns to normal conversation but continues
    /// to include resources if NEW crisis signals are detected.
    static let persistentCrisisResponse = """
    I understand you might not want to reach out right now. That's okay.

    Just know that 988 is always there when you're ready -- no pressure, no judgment. You can call, text, or chat online.

    I'll be here for the everyday stuff whenever you need me.
    """

    // MARK: - Resource Information

    /// The primary crisis phone/text number. Included in every crisis response.
    static let primaryCrisisNumber = "988"

    /// The Crisis Text Line keyword. Included in every crisis response.
    static let crisisTextLineKeyword = "HOME to 741741"
}
